/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
} from '@storybook/react-native';

import { withKnobs } from '@storybook/addon-ondevice-knobs';

const stories = require.context('../src', true, /\.stories\.(js|jsx|ts|tsx|mdx)$/);

configure(() => {
  stories.keys().forEach((filename) => {
    if (filename.includes('.stories.')) {
      return stories(filename);
    }
  });
}, module);

export { view } from '@storybook/react-native';